---
- name: Template service file
  template:
    src: althea-info-server.service.j2
    dest: /etc/systemd/system/althea-info-server.service
  become: true

- name: Set the info server to run on startup
  systemd:
    daemon_reload: yes
    name: althea-info-server
    state: restarted
    enabled: yes
  become: true

- name: Wait for Quick crashes
  pause:
    seconds: 10

- name: Check if the info server is running
  command: systemctl status althea-info-server
  ignore_errors: true
  changed_when: false
  register: service_gravity_info_server_status

- name: Report status of Althea info server
  fail:
    msg: |
      Service althea-info-server is not running.
      Output of `systemctl status althea-info-server`:
      {{ service_gravity_info_server_status.stdout }}
      {{ service_gravity_info_server_status.stderr }}
  when: service_gravity_info_server_status is failed