[package]
name = "gravity-info-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethereum_gravity = {git = "https://github.com/gravity-bridge/gravity-bridge"}
cosmos_gravity = {git = "https://github.com/gravity-bridge/gravity-bridge"}
gravity_utils = {git = "https://github.com/gravity-bridge/gravity-bridge"}
gravity_proto = {git = "https://github.com/gravity-bridge/gravity-bridge"}
deep_space = "2"
web30 = "0.19"
serde_derive = "1"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.9"
log = "0.4"
actix-web = {version = "4.2", features = ["rustls"]}
actix-cors = "0.6"
rustls = "0.20"
rustls-pemfile = "0.3"
lazy_static = "1.4"
tonic = "0.7"
futures = "0.3"
num256 = "0.3"

[features]
development = []