name: Tests for Gravity Info

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-althea-info-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "althea-info-server/"
      - name: Check rust
        run: cd althea-info-server && cargo check --all
  test-althea-info-server:
    needs: check-althea-info-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "althea-info-server/"
      - name: Run althea-info-server tests
        run: cd althea-info-server && cargo test --verbose --all
  rustfmt-althea-info-server:
    needs: check-althea-info-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check code formatting
        run: cd althea-info-server && rustup component add rustfmt && cargo fmt --all -- --check
  clippy-althea-info-server:
    needs: check-althea-info-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "althea-info-server/"
      - name: Check for Clippy lints
        run: cd althea-info-server && rustup component add clippy && cargo clippy --all --all-targets --all-features -- -D warnings

  build-althea-info-dash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build node
        run: cd althea-info-dash && yarn && yarn build --frozen-lockfile